version: '3.8'

services:
  alunosapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5113:8080"
    depends_on:
      - sql-alunos
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sql-alunos,1433;Database=AlunosDb;User ID=sa;Password=Edug0@2025!;TrustServerCertificate=True
    networks:
      - edugo_tcc_net

  sql-alunos:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Edug0@2025!
    networks:
      - edugo_tcc_net
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

networks:
  edugo_tcc_net:
    driver: bridge
