# Use a imagem base do .NET SDK para construir a aplicação
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["Alunos.API.csproj", "./"]
RUN dotnet restore "Alunos.API.csproj"
COPY . .
WORKDIR "/src/"
RUN dotnet build "Alunos.API.csproj" -c Release -o /app/build

# Use a imagem base do .NET Runtime para executar a aplicação
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS publish
WORKDIR /app
COPY --from=build /app/build .
ENTRYPOINT ["dotnet", "Alunos.API.dll"]